<?php
$kidscare_slider_sc = kidscare_get_theme_option( 'front_page_title_shortcode' );
if ( ! empty( $kidscare_slider_sc ) && strpos( $kidscare_slider_sc, '[' ) !== false && strpos( $kidscare_slider_sc, ']' ) !== false ) {

	?><div class="front_page_section front_page_section_title front_page_section_slider front_page_section_title_slider">
	<?php
		// Add anchor
		$kidscare_anchor_icon = kidscare_get_theme_option( 'front_page_title_anchor_icon' );
		$kidscare_anchor_text = kidscare_get_theme_option( 'front_page_title_anchor_text' );
	if ( ( ! empty( $kidscare_anchor_icon ) || ! empty( $kidscare_anchor_text ) ) && shortcode_exists( 'trx_sc_anchor' ) ) {
		echo do_shortcode(
			'[trx_sc_anchor id="front_page_section_title"'
									. ( ! empty( $kidscare_anchor_icon ) ? ' icon="' . esc_attr( $kidscare_anchor_icon ) . '"' : '' )
									. ( ! empty( $kidscare_anchor_text ) ? ' title="' . esc_attr( $kidscare_anchor_text ) . '"' : '' )
									. ']'
		);
	}
		// Show slider (or any other content, generated by shortcode)
		echo do_shortcode( $kidscare_slider_sc );
	?>
	</div>
	<?php

} else {

	?>
	<div class="front_page_section front_page_section_title
		<?php
		$kidscare_scheme = kidscare_get_theme_option( 'front_page_title_scheme' );
		if ( ! empty( $kidscare_scheme ) && ! kidscare_is_inherit( $kidscare_scheme ) ) {
			echo ' scheme_' . esc_attr( $kidscare_scheme );
		}
		echo ' front_page_section_paddings_' . esc_attr( kidscare_get_theme_option( 'front_page_title_paddings' ) );
		?>
		"
		<?php
		$kidscare_css      = '';
		$kidscare_bg_image = kidscare_get_theme_option( 'front_page_title_bg_image' );
		if ( ! empty( $kidscare_bg_image ) ) {
			$kidscare_css .= 'background-image: url(' . esc_url( kidscare_get_attachment_url( $kidscare_bg_image ) ) . ');';
		}
		if ( ! empty( $kidscare_css ) ) {
			echo ' style="' . esc_attr( $kidscare_css ) . '"';
		}
		?>
	>
	<?php
		// Add anchor
		$kidscare_anchor_icon = kidscare_get_theme_option( 'front_page_title_anchor_icon' );
		$kidscare_anchor_text = kidscare_get_theme_option( 'front_page_title_anchor_text' );
	if ( ( ! empty( $kidscare_anchor_icon ) || ! empty( $kidscare_anchor_text ) ) && shortcode_exists( 'trx_sc_anchor' ) ) {
		echo do_shortcode(
			'[trx_sc_anchor id="front_page_section_title"'
									. ( ! empty( $kidscare_anchor_icon ) ? ' icon="' . esc_attr( $kidscare_anchor_icon ) . '"' : '' )
									. ( ! empty( $kidscare_anchor_text ) ? ' title="' . esc_attr( $kidscare_anchor_text ) . '"' : '' )
									. ']'
		);
	}
	?>
		<div class="front_page_section_inner front_page_section_title_inner
		<?php
		if ( kidscare_get_theme_option( 'front_page_title_fullheight' ) ) {
			echo ' kidscare-full-height sc_layouts_flex sc_layouts_columns_middle';
		}
		?>
			"
			<?php
			$kidscare_css      = '';
			$kidscare_bg_mask  = kidscare_get_theme_option( 'front_page_title_bg_mask' );
			$kidscare_bg_color_type = kidscare_get_theme_option( 'front_page_title_bg_color_type' );
			if ( 'custom' == $kidscare_bg_color_type ) {
				$kidscare_bg_color = kidscare_get_theme_option( 'front_page_title_bg_color' );
			} elseif ( 'scheme_bg_color' == $kidscare_bg_color_type ) {
				$kidscare_bg_color = kidscare_get_scheme_color( 'bg_color', $kidscare_scheme );
			} else {
				$kidscare_bg_color = '';
			}
			if ( ! empty( $kidscare_bg_color ) && $kidscare_bg_mask > 0 ) {
				$kidscare_css .= 'background-color: ' . esc_attr(
					1 == $kidscare_bg_mask ? $kidscare_bg_color : kidscare_hex2rgba( $kidscare_bg_color, $kidscare_bg_mask )
				) . ';';
			}
			if ( ! empty( $kidscare_css ) ) {
				echo ' style="' . esc_attr( $kidscare_css ) . '"';
			}
			?>
		>
			<div class="front_page_section_content_wrap front_page_section_title_content_wrap content_wrap">
				<?php
				// Caption
				$kidscare_caption = kidscare_get_theme_option( 'front_page_title_caption' );
				if ( ! empty( $kidscare_caption ) || ( current_user_can( 'edit_theme_options' ) && is_customize_preview() ) ) {
					?>
					<h1 class="front_page_section_caption front_page_section_title_caption front_page_block_<?php echo ! empty( $kidscare_caption ) ? 'filled' : 'empty'; ?>"><?php echo wp_kses( $kidscare_caption, 'kidscare_kses_content' ); ?></h1>
					<?php
				}

				// Description (text)
				$kidscare_description = kidscare_get_theme_option( 'front_page_title_description' );
				if ( ! empty( $kidscare_description ) || ( current_user_can( 'edit_theme_options' ) && is_customize_preview() ) ) {
					?>
					<div class="front_page_section_description front_page_section_title_description front_page_block_<?php echo ! empty( $kidscare_description ) ? 'filled' : 'empty'; ?>"><?php echo wp_kses( wpautop( $kidscare_description ), 'kidscare_kses_content' ); ?></div>
					<?php
				}

				// Buttons
				if ( kidscare_get_theme_option( 'front_page_title_button1_link' ) != '' || kidscare_get_theme_option( 'front_page_title_button2_link' ) != '' ) {
					?>
					<div class="front_page_section_buttons front_page_section_title_buttons">
					<?php
						kidscare_show_layout( kidscare_customizer_partial_refresh_front_page_title_button1_link() );
						kidscare_show_layout( kidscare_customizer_partial_refresh_front_page_title_button2_link() );
					?>
					</div>
					<?php
				}
				?>
			</div>
		</div>
	</div>
	<?php
}
