<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Kestrel\\Store_Credit\\Scoped\\Kestrel\\Fenix\\' => array($vendorDir . '/kestrelwp/fenix/src'),
    'Kestrel\\Store_Credit\\Scoped\\Doctrine\\Deprecations\\' => array($vendorDir . '/doctrine/deprecations/src'),
    'Kestrel\\Store_Credit\\Scoped\\Doctrine\\Common\\Collections\\' => array($vendorDir . '/doctrine/collections/lib/Doctrine/Common/Collections'),
    'Kestrel\\Store_Credit\\Scoped\\CommerceGuys\\Addressing\\' => array($vendorDir . '/commerceguys/addressing/src'),
);
